FROM node:18

WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install project dependencies
RUN yarn install

# Volume will be mounted here, no need for COPY
CMD ["yarn", "dev"]