name: Sync to Hugging Face hub
concurrency: development
on:
  push:
    branches: [main]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        env:
          HF_USERNAME: ${{ vars.HF_USERNAME }}
          HF_ORGANIZATION: ${{ vars.HF_ORGANIZATION }}
          SPACE_NAME: ${{ vars.SPACE_NAME }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          DEV_TITLE_COMMIT: "0adbd649fa2138be8f754672b975a7acde1e98d5"
        run: |
          git config user.name "CoordIA Bot"
          git config user.email "(none)"
          git cherry-pick $DEV_TITLE_COMMIT
          git push https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/$HF_ORGANIZATION/$SPACE_NAME HEAD:main