name: GitHub Actions Demo
on: [push, pull_request]
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
        - name: Check out the repo
          uses: actions/checkout@v4
        - run: docker build .