name: Deployment to production (Hugging Face)
concurrency: production
on:
  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        env:
          HF_USERNAME: ${{ vars.HF_USERNAME }}
          HF_ORGANIZATION: ${{ vars.HF_ORGANIZATION }}
          SPACE_NAME: ${{ vars.SPACE_NAME }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push -f https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/$HF_ORGANIZATION/$SPACE_NAME HEAD:main